// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF9fFykN03XccA7GfQ6kgB3lvKg3qLOv4',
    appId: '1:179113158589:web:a863db9e8e7d37df9714d4',
    messagingSenderId: '179113158589',
    projectId: 'prodect-key',
    authDomain: 'prodect-key.firebaseapp.com',
    storageBucket: 'prodect-key.firebasestorage.app',
    measurementId: 'G-WYLDTZWNG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_Imt3lhoSZqvDiL-_Ohbz0zdkIuAawbY',
    appId: '1:179113158589:android:911e51390e5abdb19714d4',
    messagingSenderId: '179113158589',
    projectId: 'prodect-key',
    storageBucket: 'prodect-key.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiX_tmPlHFAX-CTKIFEU8EePfkxCg3bYQ',
    appId: '1:179113158589:ios:654b449a29c2b1cd9714d4',
    messagingSenderId: '179113158589',
    projectId: 'prodect-key',
    storageBucket: 'prodect-key.firebasestorage.app',
    iosBundleId: 'com.example.productKeyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiX_tmPlHFAX-CTKIFEU8EePfkxCg3bYQ',
    appId: '1:179113158589:ios:654b449a29c2b1cd9714d4',
    messagingSenderId: '179113158589',
    projectId: 'prodect-key',
    storageBucket: 'prodect-key.firebasestorage.app',
    iosBundleId: 'com.example.productKeyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF9fFykN03XccA7GfQ6kgB3lvKg3qLOv4',
    appId: '1:179113158589:web:382e554cc4c04d5e9714d4',
    messagingSenderId: '179113158589',
    projectId: 'prodect-key',
    authDomain: 'prodect-key.firebaseapp.com',
    storageBucket: 'prodect-key.firebasestorage.app',
    measurementId: 'G-2P48B7ZC9M',
  );
}
